### ISSUE TITLE
Use "-f all" for nmcli command

### ISSUE THREAD

**Issue by ivivona** [elqui-app/node-wifi#1]
In Debian Jessie, the nmcli command does not return the FREQ field by default. This make the code not recognise the command's output and hence the library returns no networks.

Forcing all the fields in the result with the "-f all" option will solve this problem.

**Comment by ThibaultFriedrich** [comment]
Hi,
That's right, we only tested on Ubuntu 14.04 for Linux. Thanks to you for having discover this specificity.

It has been updated and published on npm with version 1.0.3.

Please, do no hesitate to report other bugs.
