### ISSUE TITLE
wifi.scan returns SSIDs without spaces

### ISSUE THREAD

**Issue by tobeorla** [elqui-app/node-wifi#13]
**O.S:** Windows 10
**Network name:** Just a test
`wifi.scan` returns:
```json
frequency: "2412",
mac: "2a:a4:1c:95:e4:05",
security: "WPA2-Personal",
signal_level: -56.5,
ssid: "Justatest"
```

**Comment by thibaultfriedrich** [comment]
Quite weird (I thought we checked it) but I checked and you are totally right. Thx for the notice. I will correct this very quickly.

**Comment by thibaultfriedrich** [comment]
Correction done. Tell me if it is ok for you.

**Comment by tobeorla** [comment]
Yes! Closing issue.
